### ISSUE TITLE
Add support for routes

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#1]
I think we need to support routes, currently trying to move back breaks things ...

**Comment by TristanWright** [comment]
`#/project/hydra-th/` -> `/project/hydra-th/`

**Comment by TristanWright** [comment]
This is a snippet which would go in _core/module.js_ that enables it: 

```
.config(function($locationProvider) {
        $locationProvider.html5Mode({
            enabled: true,
            requireBase: false
        });
    })
```

Needs some server config though, because the server will look for a `/login` route and return 404 otherwise.

**Comment by TristanWright** [comment]
Helpful https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode 
But a browser refresh on any page still redirects to '/home', I believe there's a small setting we're missing.

**Comment by TristanWright** [comment]
Progress: In every controller we're rerouting to login if `user === null`, on login we're rerouting to home if user is ok. This route happens every time. Need to find better single-page angular practices for authentication.

**Comment by cjh1** [comment]
You might want to take a look at [this](https://github.com/OpenChemistry/mongochemclient/blob/master/app/shared/authentication/authentication.service.js) is an auth service I wrote for another project that works with routing.

**Comment by TristanWright** [comment]
Looks like a good opportunity to get some of #30 done too.
