### ISSUE TITLE
Replace occurrences of cmb with hpcc

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#10]
We have cmb in the directory structure etc. Would be nice to clean this up.

**Comment by TristanWright** [comment]
_cmb_ prefix to _hpc_ sound ok?

**Comment by cjh1** [comment]
or hpcc ? @jourdain  Any thoughts?

**Comment by jourdain** [comment]
spcc seems good

**Comment by jourdain** [comment]
hpcc ;-) Stupid auto correct

**Comment by patrickoleary** [comment]
Why not just spell the whole thing out hpccloud

**Comment by TristanWright** [comment]
To Do: 
- [ ] rename files
- [ ] rename controllers and modules
- [ ] rename references in assets folder
