### ISSUE TITLE
After terminating a viz session the sim goes into error state and viz can't be restarted

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#106]

**Comment by TristanWright** [comment]
when the viz button is reenabled, the item is still missing a [`output.hydra_job` attribute](https://github.com/Kitware/HPCCloud/blob/8cd66e80ae5909b325c98767df99c7c046f72074/src/modules/cmb/core/cmb-main-controller.js#L283)

**Comment by TristanWright** [comment]
So I'm running into this again on the head of #123

**Comment by TristanWright** [comment]
Fixed in #123
