### ISSUE TITLE
PVW seem to be creating WebGL context in image delivery mode?

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#107]
The visualizer comes up very white:
![main](https://cloud.githubusercontent.com/assets/1031053/10671354/25e18132-78b8-11e5-870b-fe1d8e8a1d2d.png)

And I see the following in the console:

![error](https://cloud.githubusercontent.com/assets/1031053/10671364/2e28bb80-78b8-11e5-9d06-a434d7ad53ba.png)

**Comment by cjh1** [comment]
@jourdain Any ideal whats happening here?

**Comment by jourdain** [comment]
Yes I do

**Comment by TristanWright** [comment]
fixed with #114, closing.
