### ISSUE TITLE
Progress indicator is needed in mesh tagger derivative

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#109]
It takes about 10 - 30 seconds of the viz to appear ( on my machine ). We need some sort of progress indicator.

**Comment by cjh1** [comment]
@jourdain Looks like you just added it?

**Comment by jourdain** [comment]
yep, pushed a spinning thing

**Comment by cjh1** [comment]
@jourdain Could we center it on the screen?

![spinner](https://cloud.githubusercontent.com/assets/1031053/10676887/17d48444-78d7-11e5-8874-c245467baa68.png)

**Comment by jourdain** [comment]
I guess we could, but will need Tristan expertise in CSS to do so.
