### ISSUE TITLE
400 (Bad Request) when accessing folder.

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#11]
I am seeing the following error when entering the nuclear simulation project:

POST http://localhost:9000/api/v1/folder?parentId=hydra-th&parentType=collection&name=websimdev&description=websimdev%27s%20projects 400 (Bad Request)

The response is:

```javascript
{"field": "id", "message": "Invalid ObjectId: hydra-th", "type": "validation"}
```

Looks like we are passing an invalid ObjectId.

**Comment by jourdain** [comment]
hydra-ne was renamed to hydra-th... Need a renaming in assets or DB. Don't remember which one.

**Comment by cjh1** [comment]
I have already renamed the collection to hydra-th, is there another place I need to do a rename?

**Comment by jourdain** [comment]
Don't remember but Tristan had to do it when it started the project. I can't remember where though.

**Comment by jourdain** [comment]
Yes, the collection name...

**Comment by TristanWright** [comment]
We renamed it through the girder interface I believe.

**Comment by cjh1** [comment]
Yup, I did the same but am still seeing the issue ....

**Comment by cjh1** [comment]
So I have dug into this some more and the problem is this [call](https://github.com/Kitware/HPCCloud/blob/master/src/modules/cmb/core/cmb-workflow-controller.js#L63-L66). We are passing the in the collection name rather than the collection id. I can added a fix to fetch the collection id.
