### ISSUE TITLE
Return to ongoing meshtagger

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#111]
Related to #70.

- Provide a meta item to the project (/folder) to inform the front end that the tagger is running
- How to detect that the tagger is no longer active and remove the meta item?

**Comment by cjh1** [comment]
@TristanWright I think if I make the change we talked about in terms of having the mesh tagger task stay in the running state until it returns will provide a way to detect when the tagger is nolonger active.

**Comment by cjh1** [comment]
@TristanWright what change has been made, the mesh tagger will stay in running state until it times out.

**Comment by TristanWright** [comment]
No changes yet on that branch, I'm going to commit it there though.
