### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#113]
Not critical, perhaps just bump the major versions, from [npm.click](http://npm.click/)

```
Up to date: 9
Minor Updates: 21
Major Updates: 19
```

The major ones are mostly gulp plugins.

**Comment by TristanWright** [comment]
It should be of some interest that [ng-material](https://github.com/angular/material/releases) is nearing 1.0

**Comment by cjh1** [comment]
Yes, it would be nice to pull in 1.0
