### ISSUE TITLE
Strange state when moving from visualizer to mesh tagger

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#120]
So I think Patrick may have seen this in the past. It you run the mesh tagger on a project and then run the visualizer for a simulation in the project. Switch back to the mesh tagger can result in a image like the one below!

![error](https://cloud.githubusercontent.com/assets/1031053/11006825/f6f3ad2c-8493-11e5-9caa-a6df1e3f25db.png)

Its as through the two session are getting mixed up or something?

@jourdain Any ideas?

**Comment by jourdain** [comment]
Seems like the rendering window size is wrong (10x10)

Probably due to the fact that the client is requesting a render while its renderer is hidden (size 0)

**Comment by jourdain** [comment]
I guess when you interact, everything come back to normal?

**Comment by cjh1** [comment]
@jourdain No, interaction doesn't fix it
