### ISSUE TITLE
meshtagger task status not always updated

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#124]
@jourdain and I have had encountered the issue to day where: 
1. Meshtagger starts fine
2. You leave and return.
3. Leave again. 
4. When you try to reconnect the task.status in the /project meta or in the direct /task object is still "running" despite the meshtagger task having already left qstat.

Basically the task statuses girder has aren't always updated after a job leaves qstat? Ideas @cjh1?

**Comment by cjh1** [comment]
Does this consistently happen?

**Comment by cjh1** [comment]
I ran though the steps described above and everything seem to work as designed, so I guess its not consistent. When it does occurs can you take a look at the celery logs?

**Comment by TristanWright** [comment]
Got the issue here again, tried running them on ulmus, there's no `/var/log/celery`?

**Comment by cjh1** [comment]
There is no celery log on the VM?
