### ISSUE TITLE
Mesh upload percentage needs to have finer grain feedback

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#125]
Currently it seem you have to wait until 50% before you know anything has happen

**Comment by jourdain** [comment]
I think it has to do with the size of the file. 
Each step is related to the chunk size that we upload. So I guess if the file is small you may need only 2-3 chunks...

**Comment by TristanWright** [comment]
Correct, you can see more updates when you upload a larger file.

**Comment by jourdain** [comment]
We can have a custom code base for chunk upload, were we use the native httpRequest where fine progress can be monitored. Unless Axios updated its code base so we can attach an 'onprogress' callback.

**Comment by cjh1** [comment]
Fixed
