### ISSUE TITLE
Configuration requirements for running PyFR

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#130]
This issue is a placeholder to start collecting some of the UI configuration requirements for PyFR. These are in addition to what we have for SimPut.

- [x] Expose number of rank in cluster, allow this to be configured at simulation runtime.
- [x] Expose number of slots per node in cluster UI
- [x] Path to pyfr, allow the path to pyfr to be configured for a cluster, this is option.
- [x] Path to cblas
- [x] Expose the backend to be used at simulation runtime. cuda, opencl, openmp.

**Comment by jourdain** [comment]
All of that should be taking care with the PyFr/Backend + the Scheduler/Config
