### ISSUE TITLE
Add support for specifying max wall clock time on submission

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#133]
maxWallTime can now be passed when a task is run

**Comment by aashish24** [comment]
@cjh1 what is maxWallTime?

**Comment by cjh1** [comment]
Its the maximum amount of time the job should take, before the scheduler will kill it.

**Comment by aashish24** [comment]
Ahh.. nice! thanks.

**Comment by jourdain** [comment]
Should be handle with the scheduler config part.
