### ISSUE TITLE
Traditional cluster configuration UI updates

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#135]
- [x] Allow the number of nodes in the cluster to be configured
- [x] Allow the number of cores per node to be configured
- [x] Allow the number of gpus per node to be configured 
- [x] Allow the job scheduler to be configured ( sge or pbs for now )
- [x] If the job scheduler is sge allow a parallel environment to be configured. (see ##134 )

**Comment by jourdain** [comment]
All should be managed now with the SchedulerConfig part
