### ISSUE TITLE
Traditional cluster simulation launch dialog updates

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#136]
- [x] Allow the job scheduler to be configured ( sge or pbs for now )

### For a cluster using PBS:

Either:
- [x] Allow the number of nodes specified, this will default to the number of nodes in the cluster.
- [x] Allow the number of cores per node to be configured, this will default to the number of core per node for the cluster.
- [x] Allow the number of gpus per node to be configured  

Or
- [x] Allow the number of cores to specified, this will default to the number of nodes * number of cores per node in the cluster.

### For a cluster using SGE:
- [x] Allow the number of gpus per node to be configured  ( this need to be documented, in that we are assuming there is a complex resource call 'gpus' setup to indicate the number of gpus for a event node )
- [x] Allow the number of cores to be specified, his will default to the number of nodes * number of cores per node in the cluster.
- [x] Allow a parallel environment to be configured. (see ##134 )

**Comment by jourdain** [comment]
We should be all set for that thanks to the Scheduler config
