### ISSUE TITLE
SimPut: Uncaught TypeError: Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#149]
To recreate:

- Click 'Input definition'
- Click 'Solver Elements +'
- Select Quadrilateral
- Change 'Solution points' to 'gauss-legendre-lobatto'

**Comment by TristanWright** [comment]
I believe this was just fixed in Simput. `npm install` should pull the latest.

**Comment by cjh1** [comment]
Running npm install didn't resolve this issue.

**Comment by TristanWright** [comment]
fixed with 93b0a7c
