### ISSUE TITLE
'Invalid Zone' when trying to create AWS profile 

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#15]
If I switch regions for example from 'us-east-1' to 'us-west-2' the POST request still sends the availability zone for the previous region in this case 'us-east-1a'.

**Comment by TristanWright** [comment]
12b5dab should fix what you're describing, I'll let you close if it does. I noticed the body I'm sending to update the does not fully match what the end point is expecting.

```
{
  "accessKeyId": "", //gets sent
  "errorMessage": "",
  "secretAccessKey": "",
  "status": "" //gets sent
}
```

**Comment by cjh1** [comment]
Thanks, I will test it out. We currently ignore an extra fields. Why are those extra fields being sent?

**Comment by TristanWright** [comment]
That's what the endpoint is expecting. I'm sending the object from the form, so `status` and `accessKeyId` are there, I was expecting parameters closer to what's in POST /user/{id}/aws/profiles

**Comment by cjh1** [comment]
OK, I see, the parameter are optional for the update. status and errorMessage are used by the celery job that creates the key pair, the client doesn't need to send them.

**Comment by cjh1** [comment]
Fixed
