### ISSUE TITLE
Additional properties are not allowed (simulations, projects)

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#160]
Getting back an error message: 
`{"message": "Additional properties are not allowed (u'description' was unexpected)", "type": "validation"}`

**Comment by cjh1** [comment]
You need to pull the latest dev-v2 in your vagrant vm. 

vagrant ssh
sudo -iu hpccloud
cd /opt/hpccloud/hpccloud
git pull origin

**Comment by TristanWright** [comment]
Thanks that worked 👍
Seb mentioned if I have a symlink to HPC-Cloud in HPCClout-deploy (
`ln -s hpccloud ~/work/HPCCloud`) It will stay in sync?

**Comment by cjh1** [comment]
You will also need to export DEVELOPMENT=1 before doing the vagrant up ....
