### ISSUE TITLE
dev-v2 branch broken

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#163]
I see the following when I do npm start:

ERROR in ./~/css-loader!./~/postcss-loader!./~/tonic-ui/lib/react/properties/Checkbox/style.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/cjh/work/source/hpccloud/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/cjh/work/source/hpccloud/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home/cjh/work/source/hpccloud/node_modules/postcss-loader/index.js:47:32)
 @ ./~/tonic-ui/lib/react/properties/Checkbox/style.css 4:14-116

ERROR in ./~/css-loader!./~/postcss-loader!./~/tonic-ui/lib/react/widget/ToggleIconButton/style.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/cjh/work/source/hpccloud/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/cjh/work/source/hpccloud/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home/cjh/work/source/hpccloud/node_modules/postcss-loader/index.js:47:32)
 @ ./~/tonic-ui/lib/react/widget/ToggleIconButton/style.css 4:14-116

ERROR in ./~/css-loader!./~/postcss-loader!./~/tonic-ui/lib/react/widget/NumberSliderControl/style.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/cjh/work/source/hpccloud/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/cjh/work/source/hpccloud/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home/cjh/work/source/hpccloud/node_modules/postcss-loader/index.js:47:32)
 @ ./~/tonic-ui/lib/react/widget/NumberSliderControl/style.css 4:14-116

And I see the following in the browser console:

Uncaught Error: Cannot find module "!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./../../node_modules/postcss-loader/index.js!./Login.mcss"webpackMissingModule @ HPCCloud.js:48358(anonymous function) @ HPCCloud.js:48358__webpack_require__ @ HPCCloud.js:20(anonymous function) @ HPCCloud.js:48244__webpack_require__ @ HPCCloud.js:20(anonymous function) @ HPCCloud.js:24666__webpack_require__ @ HPCCloud.js:20(anonymous function) @ HPCCloud.js:69__webpack_require__ @ HPCCloud.js:20(anonymous function) @ HPCCloud.js:47(anonymous function) @ HPCCloud.js:48__webpack_require__ @ HPCCloud.js:20(anonymous function) @ HPCCloud.js:40(anonymous function) @ HPCCloud.js:43
(index):13 Uncaught ReferenceError: HPCCloud is not defined(anonymous function) @ (index):13

**Comment by cjh1** [comment]
@TristanWright @jourdain I think we should start relying on travis to pick up some of these issues.

**Comment by jourdain** [comment]
Which node and npm version?

**Comment by cjh1** [comment]
npm 3.5.3
node 0.10.41

Moving to node 0.12.9 fixed the problem.

Why didn't:

  "engines": {
    "node": ">= 0.12",
    "npm": ">= 3.5"
  },

In package.json prevent things from building and warn me?

On Tue, Feb 2, 2016 at 6:44 PM, Sebastien Jourdain <notifications@github.com

**Comment by TristanWright** [comment]
The wording is unclear to me. Set 'engineStrict'? (or is it engine-strict)
https://docs.npmjs.com/files/package.json#enginestrict

On Wed, Feb 3, 2016 at 5:47 AM, Chris Harris <notifications@github.com>
wrote:

> npm 3.5.3
> node 0.10.41
>
> Moving to node 0.12.9 fixed the problem.
>
> Why didn't:
>
> "engines": {
> "node": ">= 0.12",
> "npm": ">= 3.5"
> },
>
> In package.json prevent things from building and warn me?
>
> On Tue, Feb 2, 2016 at 6:44 PM, Sebastien Jourdain <
> notifications@github.com
> > wrote:
>
> > Which node and npm version?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Kitware/HPCCloud/issues/163#issuecomment-178891275>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/issues/163#issuecomment-179205256>.
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by jourdain** [comment]
I don't know, I've never played with those config/settings.

Seb

**Comment by TristanWright** [comment]
After a bit of looking around seems enginStrict or engine-strict has no
effect.

https://github.com/TryGhost/Ghost/pull/6063
https://github.com/TryGhost/Ghost/pull/5114

We could add some *npm-check*-like tool that runs before build that will
throw if node version doesn't match.

On Wed, Feb 3, 2016 at 8:41 AM, Sebastien Jourdain <notifications@github.com
> wrote:

> I don't know, I've never played with those config/settings.
>
> Seb
>
> On Wed, Feb 3, 2016 at 8:32 AM, TristanWright <notifications@github.com>
> wrote:
>
> > The wording is unclear to me. Set 'engineStrict'? (or is it
> engine-strict)
> > https://docs.npmjs.com/files/package.json#enginestrict
> >
> > On Wed, Feb 3, 2016 at 5:47 AM, Chris Harris <notifications@github.com>
> > wrote:
> >
> > > npm 3.5.3
> > > node 0.10.41
> > >
> > > Moving to node 0.12.9 fixed the problem.
> > >
> > > Why didn't:
> > >
> > > "engines": {
> > > "node": ">= 0.12",
> > > "npm": ">= 3.5"
> > > },
> > >
> > > In package.json prevent things from building and warn me?
> > >
> > > On Tue, Feb 2, 2016 at 6:44 PM, Sebastien Jourdain <
> > > notifications@github.com
> > > > wrote:
> > >
> > > > Which node and npm version?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/Kitware/HPCCloud/issues/163#issuecomment-178891275
> > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Kitware/HPCCloud/issues/163#issuecomment-179205256
> >.
> > >
> >
> >
> >
> > --
> > - Tristan Wright
> >
> > *R&D Engineer*
> > *Kitware Inc.*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Kitware/HPCCloud/issues/163#issuecomment-179295235>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/issues/163#issuecomment-179299876>.
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by TristanWright** [comment]
fixed in 4d8493cb423836cdef5accafdf93bd0b6c12bc77
