### ISSUE TITLE
Simulations endpoint and data structure...

### ISSUE THREAD

**Issue by jourdain** [Kitware/HPCCloud#167]
Draft subject to discussion:

Simulation structure should have the following set of properties + the ones it currently have

```javascript
var simulation = {
    // Only 3 choices (User still working on it, Something is running, Data available)
    status: 'Editing | Running | Data',       

   // The active/selected step
    active: 'Simulation',

   // List of Step that the user can not enable either because already done or dependency not meet
   disabled: [ 'Visualization', 'Simput' ],

   steps: {
      Introduction: {
           type: 'information',
      },
      Simput: { 
           type: 'input',
           view: 'read-only',
            metadata: { ... }
      },
      Simulation: {
           type: 'output',
           view: 'running',
           metadata: { ... }
      },
      Visualization: {
           view: 'default',
            metadata: { ... }
      }
  }
}
```

This will imply the following set of endpoints:

PUT /simulations/{id}/steps/{name}/active
PUT /simulations/{id}/steps/{name}/enable or /simulations/{id}/enable + ['step1', 'step2'] as payload
PUT /simulations/{id}/steps/{name}/disable or same as above
PUT /simulations/{id}/steps/{name}/view/{viewName}
PUT /simulations/{id}/status/{status}

@cjh1 let me know what you think. Then we can discuss that tomorrow when I arrive to work.

**Comment by jourdain** [comment]
Or if the PUT /simulations/{id}/steps/{name}/active could have some payload to enable/disable some step, that will be even better.
{
   enable: [],
   disable:[]
}

This will prevent code like that:

```javascript
        client.enableSimulationStep(this.props.simulation, NEXT_STEP)
            .then(ok => {
                client.activateSimualtionStep(this.props.simulation, NEXT_STEP)
                    .then(resp => {
                        client.disableSimulationStep(this.props.simulation, CURRENT_STEP)
                            .then(r => {
                                this.context.router.replace(['/View/Simulation', this.props.simulation._id, NEXT_STEP].join('/'));
                            })
                            .catch(err => {
                                console.log('Error: PyFrSym/run/disable', err);
                            });
                    })
                    .catch(err => {
                        console.log('Error: PyFrSym/run', err);
                    });
            })
            .catch(ko => {
                console.log('Can not enable Viz step');
            });
```

**Comment by cjh1** [comment]
@jourdain Here is what we decided, correct me if I am wrong:

PATCH /simulations/:id with now take the following new properties:
enable: [<enabled steps in list >] 
disable:[<disable steps in list>]
active:<active step>

PATCH /simulations/:id/steps/:stepName with now take the following new properties:
views:< a free form string>

The following endpoint will be removed:
PUT /simulations/{id}/steps/{name}/active

The simulation states will be updated to:

'editing | running | data'

**Comment by jourdain** [comment]
Yes perfect. Thanks!

**Comment by cjh1** [comment]
We actually only need a single enabled/disabled property ( we can only be in one or the other !) So i will add disabled, if the step is not in this list it can be consider enabled ...

**Comment by cjh1** [comment]
@jourdain This should be resolved by  95c2293

**Comment by jourdain** [comment]
Can I still use the patch with enable:[] / disable:[] with only the delta I want to perform? Or do I need to make sure the disable list is fully set the way I want?

**Comment by TristanWright** [comment]
Closable?

**Comment by cjh1** [comment]
yes
