### ISSUE TITLE
Simput ContentEditable react conflict

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#174]
Occurs when pencil on child attribute is clicked and user tries to change the name.

![screen shot 2016-02-15 at 17 18 52](https://cloud.githubusercontent.com/assets/13318121/13063674/bcefb990-d407-11e5-8ab1-25b10ddc676b.png)

**Comment by jourdain** [comment]
You can fix that by removing any react inside your ./node_modules/**/react*.

You need to just keep the root one.

Seb

**Comment by TristanWright** [comment]
remove `HPCCloud/node_modules/**/react*`?

**Comment by TristanWright** [comment]
closed with ca0edf3456fc90380048806d894f9cd2156213a4
