### ISSUE TITLE
Build error related to simput

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#178]
ERROR in ./lib/workflows/pyfr/components/steps/Input/index.js
Module not found: Error: Cannot resolve module 'simput/lib/Labels' in /home/cjh/work/source/hpccloud/lib/workflows/pyfr/components/steps/Input
 @ ./lib/workflows/pyfr/components/steps/Input/index.js 11:14-42

ERROR in ./lib/workflows/pyfr/components/steps/Input/index.js
Module not found: Error: Cannot resolve module 'simput/lib/ViewMenu' in /home/cjh/work/source/hpccloud/lib/workflows/pyfr/components/steps/Input
 @ ./lib/workflows/pyfr/components/steps/Input/index.js 15:16-46

ERROR in ./lib/workflows/pyfr/components/steps/Input/index.js
Module not found: Error: Cannot resolve module 'simput/lib/modelGenerator' in /home/cjh/work/source/hpccloud/lib/workflows/pyfr/components/steps/Input
 @ ./lib/workflows/pyfr/components/steps/Input/index.js 19:22-58

**Comment by cjh1** [comment]
@TristanWright @jourdain We really need to find away to start catching these ....

**Comment by jourdain** [comment]
My last push should fix it. Sorry Chris about that.
