### ISSUE TITLE
Travis build error

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#181]
ca0edf3 seems to have broken our tests @jourdain could you fix this up?

**Comment by jourdain** [comment]
The issue was related to the fact that node 0.10 was running instead of 0.12+. 
Tristan fixed it right after so we don't get a random node version.

**Comment by cjh1** [comment]
Ok cool, it wasn't clear to me which commit fixed it.

**Comment by TristanWright** [comment]
092bad33efc9c0f34bddb7389090d316f9bfc2d7
