### ISSUE TITLE
simulations count for each project, active step for each simulation

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#185]
Might be more informative than either the "updated" or "created" column.

**Comment by jourdain** [comment]
Using Redux will help for that as well

**Comment by TristanWright** [comment]
The changes to do this are not straightforward. TableListing needs to be written more dynamically. 
Otherwise hindrances are minor, main one being raw project items do not have simulation counts.

If you want to try it out, saved work in branch `dynamic-table-listing` with this commit: 1b922dbd81c62d3c970d392f38452a6e142781af

**Comment by TristanWright** [comment]
closed with #476
