### ISSUE TITLE
Uncaught ReferenceError: WAMP_FEATURES is not defined

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#188]
I running into a error on current dev-v2

![error](https://cloud.githubusercontent.com/assets/1031053/13290618/73f8d41a-dae2-11e5-946f-293f45435eb8.png)

**Comment by jourdain** [comment]
Yes I've been struggling to find a correct way to solve that... But it is on my radar...

**Comment by jourdain** [comment]
What is your version of Chrome?

**Comment by cjh1** [comment]
Version 48.0.2564.109 (64-bit)

**Comment by jourdain** [comment]
I have Version 48.0.2564.116 (64-bit) and can't get that error. Although, I remember that error from a while back (months...)

Do you have an option to try another browser? I try to narrow down the issue. I know what it is causing it, but I did not found a good solution that works without side effects...

**Comment by cjh1** [comment]
Tried firefox 44.0.2, it reports the same issue

**Comment by jourdain** [comment]
Hum, I have the exact same version of firefox, and that work just fine. 

Anyway, thanks for trying this out, I guess I'll just have to find a correct way to patch Autobahn.

Thanks again...

**Comment by jourdain** [comment]
My last push should fix that. Could you try it out and let me know if that solved the issue you were seeing?

Thanks!

**Comment by cjh1** [comment]
Thanks, this has resolved it.
