### ISSUE TITLE
/opt/hpccloud/proxy.db is empty when creating new PVW session

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#189]
Trying to connect to `ws://${location.hostname}:8888/proxy?sessionId=${resp.data.metadata.sessionId}`

Looking more into it, `/opt/hpccloud/proxy.db` remains empty. Jobs seem to be all running fine before this. This was trying to run on Ulmus.

**Comment by cjh1** [comment]
d2456bb should resolve this
