### ISSUE TITLE
Error when starting ParaViewWeb viz

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#191]
I am seeing the following when I try to start the visualizer: 

![error](https://cloud.githubusercontent.com/assets/1031053/13325617/94b59462-dbb0-11e5-8502-14322dcb2972.png)
![error2](https://cloud.githubusercontent.com/assets/1031053/13325622/9a5bc58a-dbb0-11e5-904a-0f6f0d058e4e.png)

If you are trying to list the tasks, the url should be:

/taskflows/<taskflow_id>/tasks

**Comment by TristanWright** [comment]
fixed with https://github.com/Kitware/paraviewweb/pull/21
