### ISSUE TITLE
There is no way to tell which what workflow type it is

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#197]
_"Am I in PyFr, Paravieweb? What's the name of this project? What did I click on again[?](https://media.giphy.com/media/jcxtvm2bsZDH2/giphy.gif)_

![screen shot 2016-02-29 at 15 33 52](https://cloud.githubusercontent.com/assets/13318121/13411356/e29d830a-def9-11e5-898f-78d48339c896.png)

**Comment by TristanWright** [comment]
related #172

**Comment by jourdain** [comment]
We should start using Redux so we can have a single data model which will ease things out for handling this use case. 

For instance once we dive into a project, the project name/type can be put in the middle of the top bar or event in the title bar of the browser.

**Comment by TristanWright** [comment]
- [x] can tell simulation project name
- [ ] can tell project type

**Comment by TristanWright** [comment]
Can determine project type through other cues. closing.
