### ISSUE TITLE
metadata for simulation?

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#199]
The only metadata we can place in a simulation in an individual step. Should there be a top-level metadata container for items like input/output folder and meshes? Or should we save the metadata to a step which we specify somewhere?

**Comment by cjh1** [comment]
I am happy to add a meta property to the simulation if its needed by the client, it shouldn't that too long.

**Comment by cjh1** [comment]
@TristanWright I have added this in #200
