### ISSUE TITLE
We need to make it clear how a simulation is started

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#2]
Every time I try to start a simulation I have trouble finding the correct button ...

**Comment by jourdain** [comment]
Yes... ;-)

**Comment by TristanWright** [comment]
If the annotation is valid, enabled a button to the panel which runs it. Hopefully these panel buttons don't keep stacking up...
```
| Start | Annotate | Clone | Download |                          | Delete | Terminate |
```

**Comment by cjh1** [comment]
Looks good, it didn't make sense that you have to go the the annotate page in order to run the simulation.
