### ISSUE TITLE
Add another simulation type

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#20]
It would be nice to be able to run another simulation as well has hydra, @jourdain and @patrickoleary can probably advise here.

**Comment by jourdain** [comment]
Yes, if you think it could be easy to run the chemistry one that you are familiar with. That would be nice.
And of course any other sim that we have experience with.

**Comment by patrickoleary** [comment]
maybe schedule a meeting with marcus to discuss.
