### ISSUE TITLE
Unable to rerun pyfr simulation

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#203]
I see the following in the console:
![console](https://cloud.githubusercontent.com/assets/1031053/13506021/f658d3de-e149-11e5-8016-4b503d847068.png)

**Comment by TristanWright** [comment]
This comes from the component unmounting and calling .unsubscribe on monologue.js. @jourdain ?

**Comment by TristanWright** [comment]
closed with 2fb71444202748a63ada768f067d8eedd685c4de
