### ISSUE TITLE
pyfr input folder doesn't contain pyfr.ini

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#204]
The folder passed to the pyfr task flow doesn't contain ini file?

**Comment by TristanWright** [comment]
working on this, issue points to here, testing it now
https://github.com/Kitware/HPCCloud/commit/c463e7442cb3eebf0a8a34ee75ebcd25a1d97102#diff-c98089493a98f571e58bbac982b5da80R13
