### ISSUE TITLE
View output files when simulation ends (errors, terminates, or completes)

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#206]

**Comment by TristanWright** [comment]
I'm not finding anything in the output folder after a simulation has been completed. There are some `.pyfrm`'s in the input folder though?

**Comment by cjh1** [comment]
0c8dd6d should resolve this

**Comment by TristanWright** [comment]
Making sure I have this process right (I wrote it down once but lost it >.<) 

- get output directory from simulation
- getItem(folderId) -> forEach item in folder provide a download link to `/api/v1/file/${file._id}/download`
