### ISSUE TITLE
Running simulation  view should show state of cluster and cluster log

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#208]

**Comment by cjh1** [comment]
Here is rough out line of what the panel should look like:

https://kitware.mybalsamiq.com/projects/hpccloud/Cluster%20panel

To start with it should appear in the JobMonitor view for a simulation. If a cluster is created as part of a taskflow it will update the metadata items clusters with a list of cluster ids. A cluster panel should be created for each of these clusters. The log entries for each cluster can be receive by connecting the following event stream:
```
GET /clusters/{id}/log/stream
```

**Comment by cjh1** [comment]
The cluster to monitor for a given taskflow can be found in the taskflow meta data (meta.cluster) Note that in the case of the EC2 cluster will not be set until the taskflow has been started. 

This item should probably be meta.clusters and hold a list of clusters. We can fix this after we have the basics work, but you should probably keep in mind that there could be multiple clusters associated with a workflow.

**Comment by cjh1** [comment]
@TristanWright What the state of this issue, I think you have a branch some where? It would be good to get this in as its need to EC2 clusters.

**Comment by TristanWright** [comment]
I have it in a local branch, I'll push it here and go back to working on it.
