### ISSUE TITLE
Would be good to be able to delete multiple simulations at once

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#211]
Having to go into each simulation to delete can be a little time consuming if there are many simulations. We might want to add a "select all" checkbox in the simulation list view and the a delete option.

**Comment by TristanWright** [comment]
Could select items using meta+click and which would toggle a delete button at the top. e.g. wunderlist: 

<img width="1102" alt="screen shot 2016-03-07 at 10 59 08" src="https://cloud.githubusercontent.com/assets/13318121/13578187/a11fa818-e453-11e5-8197-9873ed6c45fa.png">

**Comment by cjh1** [comment]
Thats the sort of interaction I was thinking of
