### ISSUE TITLE
Ensure that when a user registers the correct directory structure is create for them

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#23]
Our deployment script creates a directory in the hydra collection and gives them access to it. @jourdain Why do we store the user data under the hydra collection? Doesn't it make more sense to store this user specific data under the user?

**Comment by jourdain** [comment]
So the "data" is associated with a workflow.

**Comment by cjh1** [comment]
So does that user directory get create by the client?

**Comment by jourdain** [comment]
yes when a user goes into a given workflow for the first time.

**Comment by cjh1** [comment]
@jourdain The problem with having these user directories under the workflow is that we explicitly need to grant write access to them for the user. If a user registers, using the register link they will not be in the right group and thus will not have access the workflow directory so they creation of the user directory will fail.

**Comment by jourdain** [comment]
If the user request to be part of a group at registration time. Then that might solve part of the problem.

**Comment by cjh1** [comment]
The user doesn't have the option to request being part of a group at registration time, we would have to do this as some sort of post registration step.

**Comment by cjh1** [comment]
Or have a custom registration endpoint.

**Comment by cjh1** [comment]
I think we should discuss this in person, I still feel in may ways this data belongs in the users private folder ( is could be under a folder with the workflow name ). If the user creates simulation in several workflow their data is distributed across several collections, rather than being held on one place.
