### ISSUE TITLE
Unnecessary scroll bars

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#255]
![scroll](https://cloud.githubusercontent.com/assets/1031053/13855661/e45f75b2-ec47-11e5-8c20-846f0fbd7f1a.png)

**Comment by TristanWright** [comment]
Happens in OSX too but `System Preferences > General > Show scroll bars` must be set to `always`

![screen shot 2016-03-18 at 12 17 57](https://cloud.githubusercontent.com/assets/13318121/13887823/7b136b4c-ed03-11e5-8cc9-13aea2e30ab9.png)

**Comment by TristanWright** [comment]
Just on pages with that sort of split view...
