### ISSUE TITLE
Output files not updated when simulation completes

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#279]
A page refresh seems to be required.
![files](https://cloud.githubusercontent.com/assets/1031053/14050541/0b2a6bf6-f293-11e5-8fee-7c00abdd59a8.png)

**Comment by cjh1** [comment]
Its not just when the simulation complete, sometimes they don't appear if I navigate to a completed simulation.

**Comment by cjh1** [comment]
The console seems to show some cancelled requests:

![console](https://cloud.githubusercontent.com/assets/1031053/14050960/e7cb0834-f295-11e5-9ecb-f359d37d6b88.png)

**Comment by TristanWright** [comment]
PR #295 closes
