### ISSUE TITLE
Running cluster/server preference page

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#282]
Do we have a mockup for this? Are there to be anymore controls beyond a simple listing of the clusters/servers which are active?

**Comment by cjh1** [comment]
No, not at the moment. I can create some if that would be helpful. The minimum we need is:
- When launching a simulation on a ec2 cluster we to be able to select the node type and the size of the cluster. ( we can add create volumes later ). These will need to be passed to taskflow.
- In the simulation running view we need to add another section ( after Simulation Task ). The will display the cluster log and status. There is specific event stream for the cluster log messages: 

GET /clusters/{id}/log/stream

We can have this cluster section for both ec2 and trad clusters.
