### ISSUE TITLE
Redux migration

### ISSUE THREAD

**Issue by jourdain** [Kitware/HPCCloud#288]
Need to convert 

- [x] workflows/visualizer/*
- [x] workflows/pyfr/pyfr-simput/components/steps/Input/index.js
- [x] panels/FileListing

Other fixes:
- [x] Need to fix Simulation status change (need a different strategy)
- [x] Visualizer using Redux + integration
- [x] Button status when network call...
- [x] Workflow Log in job monitor

**Comment by TristanWright** [comment]
new PVW visualizer will close this.

**Comment by TristanWright** [comment]
fixed with #493
