### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#289]
@jourdain @TristanWright 

I am seeing the following on master

ERROR in ./src/pages/Preferences/ServerStatus/index.js

/home/cjh/work/source/hpccloud/src/pages/Preferences/ServerStatus/index.js
  50:45  error  'ec2' is missing in props validation           react/prop-types
  50:49  error  'ec2.map' is missing in props validation       react/prop-types
  51:45  error  'clusters' is missing in props validation      react/prop-types
  51:54  error  'clusters.map' is missing in props validation  react/prop-types

✖ 4 problems (4 errors, 0 warnings)

ERROR in ./src/workflows/visualizer/components/steps/Visualization/View/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../../../../network/TaskflowManager in /home/cjh/work/source/hpccloud/src/workflows/visualizer/components/steps/Visualization/View
 @ ./src/workflows/visualizer/components/steps/Visualization/View/index.js 27:23-75

ERROR in ./src/panels/JobMonitor/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../network/TaskflowManager in /home/cjh/work/source/hpccloud/src/panels/JobMonitor
 @ ./src/panels/JobMonitor/index.js 11:23-63
webpack: bundle is now VALID.

**Comment by TristanWright** [comment]
I have those ec2/cluster errors fixed in my copy.

The JobMonitor and the FileListing are in fairly incomplete states right
now we maybe shouldn't have merged the redux branch we did yesterday.

On Wed, Mar 30, 2016 at 6:19 AM, Chris Harris <notifications@github.com>
wrote:

> @jourdain <https://github.com/jourdain> @TristanWright
> <https://github.com/TristanWright>
>
> I am seeing the following on master
>
> ERROR in ./src/pages/Preferences/ServerStatus/index.js
>
> /home/cjh/work/source/hpccloud/src/pages/Preferences/ServerStatus/index.js
> 50:45 error 'ec2' is missing in props validation react/prop-types
> 50:49 error 'ec2.map' is missing in props validation react/prop-types
> 51:45 error 'clusters' is missing in props validation react/prop-types
> 51:54 error 'clusters.map' is missing in props validation react/prop-types
>
> ✖ 4 problems (4 errors, 0 warnings)
>
> ERROR in
> ./src/workflows/visualizer/components/steps/Visualization/View/index.js
> Module not found: Error: Cannot resolve 'file' or 'directory'
> ../../../../../../network/TaskflowManager in
> /home/cjh/work/source/hpccloud/src/workflows/visualizer/components/steps/Visualization/View
> @ ./src/workflows/visualizer/components/steps/Visualization/View/index.js
> 27:23-75
>
> ERROR in ./src/panels/JobMonitor/index.js
> Module not found: Error: Cannot resolve 'file' or 'directory'
> ../../network/TaskflowManager in
> /home/cjh/work/source/hpccloud/src/panels/JobMonitor
> @ ./src/panels/JobMonitor/index.js 11:23-63
> webpack: bundle is now VALID.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/issues/289>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
yes, keeping master building would be good.

**Comment by TristanWright** [comment]
Likewise, I'm a bit confused why travis didn't/doesn't catch these.

On Wed, Mar 30, 2016 at 8:12 AM, Chris Harris <notifications@github.com>
wrote:

> yes, keeping master building would be good.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/issues/289#issuecomment-203450346>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
@TristanWright Does viz-and-build-fixes fix the build issues? If so can we merge it?

**Comment by TristanWright** [comment]
Doesn't fix the file listing, but yes otherwise, will merge.

**Comment by TristanWright** [comment]
closed with #290, #292
