### ISSUE TITLE
visualizer workflow show empty screen when job is running

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#297]
I am seeing the following after I run the simulation/visualizer:

![empty](https://cloud.githubusercontent.com/assets/1031053/14183214/0a9b6ba0-f73d-11e5-8430-348a3d530f2a.png)

**Comment by TristanWright** [comment]
I haven't seen this anymore. Close?

**Comment by cjh1** [comment]
yes, I think @jourdain resolved this
