### ISSUE TITLE
Unrendered template are displayed on load ( see screenshot )

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#3]
I know there is a way fixing this but can't remember it ;-)
![untitled](https://cloud.githubusercontent.com/assets/1031053/9766789/c89e4334-56e8-11e5-9b8c-923c0c5bf3cd.png)

**Comment by jourdain** [comment]
Does that stay that way, or is it just for a few millisecond at startup?
Wondering if there is any error in fetching JS dependencies ?
Otherwise, I'm not aware of any magic that could take care of it like that...

**Comment by patrickoleary** [comment]
I only saw this when all utilities weren't started correctly or in sync.

**Comment by cjh1** [comment]
OK it took my brain a few hours but I remembered what we need here :smile_cat: [ngCloak](https://docs.angularjs.org/api/ng/directive/ngCloak)
