### ISSUE TITLE
Unable to switch between 'Introduction' and 'Simulation' in PyFR workflow

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#302]
I see the following errors in the console:

![error](https://cloud.githubusercontent.com/assets/1031053/14187627/f3f2bbf0-f751-11e5-9e55-6a397d34b285.png)

A refresh of the browser renders the correct page.

**Comment by TristanWright** [comment]
I've tracked it down to something in the SchedulerConfig/SGE.js but I cannot see a syntax error.

**Comment by cjh1** [comment]
Is there a reason the browser is not reported the syntax error?

**Comment by TristanWright** [comment]
It could be a JSX/React error not a js/browser one. Could be with how we're mounting and unmounting them.

**Comment by TristanWright** [comment]
I'm going through and checking the JSX `key={ }` attributes. There are a few places where they may not be specific enough and that could be causing this (and other) errors.

**Comment by TristanWright** [comment]
changes in #328 have no effect.

**Comment by TristanWright** [comment]
Trying out React 15.0.0, everything is smooth sailing but this behavior still occurs. However the debug output is more helpful and it doesn't lock up the app anymore! 

![screen shot 2016-04-07 at 16 06 02](https://cloud.githubusercontent.com/assets/13318121/14368358/75f1fe8a-fcda-11e5-88ab-88f138491ae5.png)

Investigating more...

**Comment by TristanWright** [comment]
`Cannot read property 'backend' or null`... might be related to #303??

**Comment by cjh1** [comment]
So this was tricky one to track down, thanks for your perseverance! It seems that upgrading to React 15 was how we got enough information to resolve it. @TristanWright do you think we should upgrade to 15 to make it easier to resolve these sort of issues in the future? What would be involved in upgrading, just updating package.json?

**Comment by TristanWright** [comment]
I would like to upgrade but I'm not sure how it will fully affect our other react dependencies (router, redux) it only came out yesterday afterall. 15 helped with #302, but it gives the same `Cannot read property '_currentElement' of null` error for the Input step.  I've updated the commit message locally and will be going back to #303 and #326 for now.
