### ISSUE TITLE
There is no way to terminate a PyFR viz session

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#305]
I only see a 'Visualize' button

![viz](https://cloud.githubusercontent.com/assets/1031053/14188600/6d9f01de-f757-11e5-8958-4ad9f125d4d4.png)

**Comment by jourdain** [comment]
Refresh it is due to the allComplete state transition issue that I'm
working on...

**Comment by TristanWright** [comment]
fixed in #315
