### ISSUE TITLE
No terminate button when navigating back to simulation view from ParaViewWeb view

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#319]
I think its related to the websocket error I am seeing in the console:

![console](https://cloud.githubusercontent.com/assets/1031053/14257052/c2759e7e-fa69-11e5-9931-5b2a8a4a5c3e.png)

**Comment by TristanWright** [comment]
I've been getting a websocket error on the PVW tool too. On a connection rather.
