### ISSUE TITLE
Add logging information to simulation

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#32]
The task resource has a log property that we should expose to the user. The property is of the following form:

```javascript
  "log": [
    {
      "$ref": "http://ulex:9001/api/v1/jobs/56030771f657105ab7913b18/log", ...
    }
```

This is basically an aggregate log of all the resource create by the task for example the cluster and jobs that are submitted to it. So the pseudo code for tail the task log would be as follows:

while task is running:
  fetch task:
    for each log in task['log']:
      fetch log provide offset of lines already fetched:
        add lines to log in ui

The log entries from the resources are of the following form:

```javascript
{
      "args": [],
      "created": 1442957579.78141,
      "exc_info": null,
      "exc_text": null,
      "filename": "job.py",
      "funcName": "_tail_output",
      "levelname": "INFO",
      "levelno": 20,
      "lineno": 288,
      "module": "job",
      "msecs": 781.4099788665771,
      "msg": "Skipping tail of 5601c8e4f657105a8f7ce936/output/stat.txt as file doesn't currently exist",
      "name": "starcluster",
      "pathname": "/home/cjh/work/source/cumulus/cumulus/starcluster/tasks/job.py",
      "process": 22983,
      "processName": "Worker-2",
      "relativeCreated": 1952257.1358680725,
      "thread": 139862483904320,
      "threadName": "MainThread"
}
```

For now I think we what to present the following information:

<created> <levelname> <msg>

With created converted to a human readable format.  I might be nice to allow a user to double click on an entry which would reveal all the log information.

**Comment by TristanWright** [comment]
formatted: `[created] name: msg`

**Comment by TristanWright** [comment]
Related to #16?

**Comment by TristanWright** [comment]
Getting a 405 here
```
XMLHttpRequest cannot load http://localhost:8080/api/v1/cluster/560b0660d80e0bcb1979455e/log. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. The response had HTTP status code 405.
```

**Comment by cjh1** [comment]
Ok, I will take a look, those URLs should probably be relative rather than full.

**Comment by cjh1** [comment]
@TristanWright I have push a fix to cumulus that makes these URLs relative, so you will just need to add them to $girder.getApiBase()

**Comment by TristanWright** [comment]
Still getting an absolute url from `tasks/{id}`?

**Comment by cjh1** [comment]
For an existing simulation?

**Comment by TristanWright** [comment]
![screen shot 2015-09-30 at 09 52 38](https://cloud.githubusercontent.com/assets/13318121/10198390/033c7fbc-6759-11e5-8319-c0b87e5a18e9.png)

For a running one.

**Comment by TristanWright** [comment]
formatted: `[created] levelname: msg`
[created] should be human readable.
