### ISSUE TITLE
too much fetching?

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#322]
On a new simulation start, over the course of ~3 seconds we make 279 filesystem, log and status calls. 
![screen shot 2016-04-05 at 12 35 36](https://cloud.githubusercontent.com/assets/13318121/14293672/d87e87b4-fb2a-11e5-9d03-f26cb12b8e89.png)

Later on in the simulation process we're making 57 calls on log and status updates.
![screen shot 2016-04-05 at 12 36 51](https://cloud.githubusercontent.com/assets/13318121/14293700/f279eb90-fb2a-11e5-8d80-67c7bc915767.png)

Is it important to be refetching all the files, logs/statuses whenever something changes?

**Comment by TristanWright** [comment]
related #308

**Comment by cjh1** [comment]
I think the answer it yes. The load time shouldn't be dependent on the number of projects or complexity of the output. The data above seem to suggest that if we have 10x times the number of projects its going to take 10x the time to load? We should only be loading project specific data when the user is in that project, likewise with a simulation and viewing the output of a simulation.
