### ISSUE TITLE
Error messages remain after a problem has been resolved

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#325]
For example try deleting a project with a simulation in it. You will get the following:

![error](https://cloud.githubusercontent.com/assets/1031053/14324689/d2ec1702-fbf3-11e5-8d22-228ac3adc282.png)

Now delete the simulation and try to delete the project, you will still see:

![error](https://cloud.githubusercontent.com/assets/1031053/14324719/f989b586-fbf3-11e5-8a11-be317116fcad.png)

Even though you can successfully delete the project.

**Comment by TristanWright** [comment]
Network related errors persist. Going to fix this in #323
