### ISSUE TITLE
PyFr ( simput workflow ) can't switch to input step

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#326]
After clicking on the input step I see the following in the console, the view doesn't switch to the input view.

![error](https://cloud.githubusercontent.com/assets/1031053/14325007/5530d4b8-fbf5-11e5-9b60-7881e465b351.png)

Refreshing the page updates the view to the input view.

**Comment by TristanWright** [comment]
I want to say related #302, or it's a very similar bug anyway.

**Comment by TristanWright** [comment]
The same thing happens from Input -> Simulation, even gets the same `traverseParentPath` error. 

![screen shot 2016-04-06 at 13 53 39](https://cloud.githubusercontent.com/assets/13318121/14330673/e70a537e-fbfe-11e5-92b4-70a2de501efb.png)

Shows a very odd view too:
![Uploading Screen Shot 2016-04-06 at 13.53.46.png…]()
