### ISSUE TITLE
Job or task log panels are closes on state change

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#332]
If you have a job or task log open such as:

![panel](https://cloud.githubusercontent.com/assets/1031053/14393363/a92aa1ca-fd94-11e5-992c-7c07afc6505e.png)

If the state of the job or task changes then the panel is minimized, which can be a little annoying if you are try to watch the log. I think the min/max state should only be controlled by the user.

**Comment by TristanWright** [comment]
closed with #409 (?)
