### ISSUE TITLE
Simulation "Visualize" button does not always go to the visualization step

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#336]

**Comment by cjh1** [comment]
@TristanWright This seems to be a performance issue, it looks like the client is now creating a large number of requests for a simple operation such as create a simulation. Its as though the whole application state is being refreshed. For example this is what I am seeing for creating a paraview sim, 1071 requests !
![requests](https://cloud.githubusercontent.com/assets/1031053/14435188/8e109870-ffe4-11e5-8989-544700ed4d34.png)

**Comment by cjh1** [comment]
#322

**Comment by TristanWright** [comment]
1071 requests in ~6 seconds, crazy!

On Mon, Apr 11, 2016 at 11:00 AM, Chris Harris <notifications@github.com>
wrote:

> #322 <https://github.com/Kitware/HPCCloud/issues/322>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/issues/336#issuecomment-208449872>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
Definitely related to #322, if I remove all my sims ( i had about 6 ), then the request storm dies down. We definitely shouldn't be touching simulations that the user isn't currently working with.

**Comment by TristanWright** [comment]
Can probably close this, but will lean on the side of caution for now.
