### ISSUE TITLE
'session not open' error when connection to ParaViewWeb session

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#338]
The console shows the following:

![error](https://cloud.githubusercontent.com/assets/1031053/14437903/7b01cc56-fff1-11e5-9142-200e33fd627f.png)

**Comment by cjh1** [comment]
Note refresh the page causes a successful connection.

**Comment by TristanWright** [comment]
Have we seen this with the new visualizer?

**Comment by cjh1** [comment]
No not recently, I think we can close this and reopen if necessary.
