### ISSUE TITLE
Deleting a simulation in the UI does not call the tasks delete endpoint

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#35]
To clean up resources associated with a task the following endpoint should be called:

DELETE /tasks/<task_id>

**Comment by TristanWright** [comment]
It seems the item does not initially have a taskId. taskId is assigned when the item status is running. Should items have a taskId earlier? The `deleteTask` call is a bit convoluted too, calling two GET's until calling DELETE and only if there's a jobId or a clusterId associated with the item.

**Comment by cjh1** [comment]
My understanding is the item will only have a taskId after the simulation has been started. @jourdain Do you know why we have these two GET calls before the DELETE.

**Comment by jourdain** [comment]
I think it has to do with getting the proper timing information, once things are "done" before deleting that information for ever.

**Comment by TristanWright** [comment]
Why is fetching the timing information necessary if it's going to be deleted forever?

**Comment by jourdain** [comment]
I guess that was to report that back up to the project, so you can compute the actual cost of a project.
Never done that loop though...

**Comment by TristanWright** [comment]
@cjh1 is this issue closeable?

**Comment by cjh1** [comment]
Yes, we now seem the cleaning up tasks
