### ISSUE TITLE
new workflow type

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#350]
It will be interesting to see how simple or difficult it will be to add new workflow types, better sooner than later. Flesh out CodeSaturne more?

**Comment by cjh1** [comment]
The plan is to add [NWChem](http://www.nwchem-sw.org/)

**Comment by cjh1** [comment]
[Avogadro 2](http://www.nwchem-sw.org/) has and input generator we can use as a model.

**Comment by cjh1** [comment]
Here is screenshot of the input generator for NWChem in Avogadro 2:

![Uploading nwchem.png…]()

**Comment by TristanWright** [comment]
On NWChem for a simulation:
- You could upload molecule file and it would be added to the simulation file what could be used with input. 
- On the 'exec' you would just upload the input file with the molecule inline.

**Comment by TristanWright** [comment]
closed with #463
