### ISSUE TITLE
move Toolbar out of workflow components

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#352]
https://github.com/Kitware/HPCCloud/blob/master/src/workflows/pyfr/common/root/ViewSimulation.js#L52-L62 

related #349

**Comment by jourdain** [comment]
If you that you will run into issue with the Visualizer

**Comment by jourdain** [comment]
maybe

**Comment by jourdain** [comment]
The point was to give more control regarding the content of the page and toolbar for a simulation.

**Comment by TristanWright** [comment]
closed with #470
