### ISSUE TITLE
Even less network calls

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#353]
We don't need all simulations and clusters (etc...) if the user just loads the project page.

**Comment by TristanWright** [comment]
(sp) fewer?

**Comment by TristanWright** [comment]
Almost got this, the trick is populating the store from just the simulationId when a simulation view loads.

**Comment by TristanWright** [comment]
I'd say moving the status and log notifications closes this. We only ever fetch logs and statuses when a view is mounted, after that it's updated with notifications.

**Comment by cjh1** [comment]
Yes, I agree
