### ISSUE TITLE
Test something

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#355]
Testing complex user interaction and the outcomes is difficult. But because we have the state nicely within redux and all the routes with in react-router something as simple as making sure all the components and pages load and function properly could be useful. I've been thinking about it a lot and I would like to try _something_ with this.

**Comment by patrickoleary** [comment]
Hmmm

**Comment by TristanWright** [comment]
I looked a bit at [Gor](https://github.com/buger/gor) yesterday. It's written in Go, but something like that to simulate or replay network calls would be nice.

**Comment by TristanWright** [comment]
I've found [nock](https://www.npmjs.com/package/nock) which looks like it could substitute for Gor.

**Comment by TristanWright** [comment]
Breakdown what we want to test. We've written tests for individual components for the `pvw` lib but the results of the tests weren't too helpful in continuing development. Here we have a many more layers, we can break them down:

- [ ] network calls and their interaction with redux
- [ ] components and their interaction with redux
- [ ] react-router pages
- [ ] all of our panel components, I'm hesitant about this one. Again component tests weren't too helpful in pvw maybe there's a different approach that will be more helpful to us here.

**Comment by TristanWright** [comment]
It's been an interesting foray in to tests. I can test basic redux actions and the results of their reducers, however async actions with _nock_ aren't straightforward or correct. Work-arounds (funky webpack hacks) have been unsuccessful, I'll be looking into mocking a server with an actual remote api to it.
