### ISSUE TITLE
Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#365]
I am setting the following when try to create a paraview project.

HPCCloud.js:47139 Uncaught (in promise) TypeError: Cannot convert undefined or null to object(…)

**Comment by TristanWright** [comment]
O_o you're getting a lot of strange errors this week. I don't think it's related but some package stuff was bumped a few days ago, have you run `npm install` recently?

**Comment by cjh1** [comment]
I am all about the strange error :-) I will try npm install ( haven't done
one recently )

Chris

**Comment by TristanWright** [comment]
changes [here](https://github.com/Kitware/HPCCloud/pull/362/commits/19be77c3d6ca8b7e6e7c3bbf47be2297bfc4903e#diff-4a90a343d7b5582d2e40d1f2d73e44cfR96) should clear this up
