### ISSUE TITLE
Error trying to start EC2 cluster for paraview workflow

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#372]
@TristanWright Looks like we need the same fix, you did for PyFR? ( is it not the same code ?)

HPCCloud.js:53512 Uncaught Error: missing `machine` in ec2 cluster payload

**Comment by TristanWright** [comment]
hmm that should be acting the same, a debug `componentWillUpdate` says otherwise, looking into it.

**Comment by TristanWright** [comment]
I was on the wrong branch, but there was something off with the payload.

**Comment by TristanWright** [comment]
closeable?
