### ISSUE TITLE
"Jobs count" shows number of running "Workflow tasks"

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#380]
The summary on the left of jobs, shows the number of running "workflow tasks" rather than the number of  jobs? See below:

![jobs](https://cloud.githubusercontent.com/assets/1031053/15125817/d0a4c048-15fc-11e6-8192-25a58f5cf15b.png)

I think this number should be move to "Worflow tasks" and the real value be displayed for jobs?

**Comment by TristanWright** [comment]
closed with #508
