### ISSUE TITLE
Travis build failing intermittently

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#383]
Example of failure:

https://travis-ci.org/Kitware/HPCCloud/jobs/128958488

**Comment by cjh1** [comment]
Looks like webpack can't be found or wasn't installed correctly.

**Comment by TristanWright** [comment]
Only the first time through though. Could be some cache issue?

**Comment by cjh1** [comment]
I just cleared the caches to see if that helps.

**Comment by TristanWright** [comment]
closed in #385
