### ISSUE TITLE
Add expose/hide option for log entries

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#386]
Some of the ansible log entries are pretty big ( the data field ) adding something like, Travis has would be good:

![travis](https://cloud.githubusercontent.com/assets/1031053/15162466/07a0f5e2-16d1-11e6-8156-34b5db14fa33.png)

Here is a example of an ansible message:

![msg](https://cloud.githubusercontent.com/assets/1031053/15162539/70ae4332-16d1-11e6-8aec-96c893297e67.png)

**Comment by TristanWright** [comment]
Theirs goes basically: 
```html
<pre>
  <p>Log entry...</p>
  <div class="fold-start">
    <p>Log entry...</p>
    <p>Log entry...</p>
  </div>
</pre>
```
Simpler than I expected.
