### ISSUE TITLE
Allow smaller output files to be view directly in the browser

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#387]
For example the stdout and stderr file for a simulation. The screenshot below shows a possible location for such an option.
![add](https://cloud.githubusercontent.com/assets/1031053/15162951/cc41080e-16d3-11e6-9272-0bceb8b852b4.png)

**Comment by TristanWright** [comment]
- Is there a file content fetching endpoint? There's `PUT /file/{id}/contents` is there a GET?
-  What's a good cutoff for the viewable size? 1MB, 2?

**Comment by TristanWright** [comment]
closed with #390
