### ISSUE TITLE
Expose project sharing in UI

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#398]

**Comment by TristanWright** [comment]
via `PUT /projects/{id}/share`
- only on project level
- read only
- non-owners can clone
- analogy: like a shared folder in google drive, all of owner's items are read-only to whom they share it with. The recipients of the folder cannot directly modify the files, but they can clone them and modify them themselves.

**Comment by TristanWright** [comment]
This should've been an early question but can you "unshare" a project or simulation with someone, or is it fixed once shared?

**Comment by cjh1** [comment]
Yes, I think sharing should be dynamic. Sharing should also be possible with a group as well as a specific user.

**Comment by TristanWright** [comment]
closed with #584
