### ISSUE TITLE
Move access to HPCCloud server endpoint out of paraviewweb repo

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#399]
They should be here.

**Comment by TristanWright** [comment]
Working through this this afternoon. Testing and ironing out.

**Comment by cjh1** [comment]
Awesome!

**Comment by TristanWright** [comment]
I think it's mostly cleared up. There may be a few misnamed functions which we're calling but they're easy to clean up. I have a local copy of the old network/client calls so if these errors happen I can find what it should now be calling instead. Example:

![screen shot 2016-05-19 at 16 21 42](https://cloud.githubusercontent.com/assets/13318121/15411504/b64a590e-1ddd-11e6-9669-402ffb968536.png)
