### ISSUE TITLE
Task log doesn't update on error

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#401]
If an error occurs the log entries are updated, a page refresh is required. The screenshot below shows an error has occurred:

![error](https://cloud.githubusercontent.com/assets/1031053/15326295/6be8431c-1c1b-11e6-8ccb-c69ba58c2b2d.png)

After a page fresh I see:

![refresh](https://cloud.githubusercontent.com/assets/1031053/15326304/76ae17a4-1c1b-11e6-865d-95cb11d03d82.png)

**Comment by TristanWright** [comment]
Played with this between two tabs, the log isn't being updated in the original hmmmm
![screen_shot_2016-05-17_at_18_05_43](https://cloud.githubusercontent.com/assets/13318121/15343438/fb80fd00-1c59-11e6-9c5f-9f9b0fcd7ae9.png)

**Comment by TristanWright** [comment]
@cjh1 
The issue is in task and job logs.
What should trigger a log fetch? A toggle open could, but when it's open how should it know when to be updated? Polling?

**Comment by TristanWright** [comment]
closed with #409 (?)
