### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#406]
(todo list moved to #452)

**Comment by cjh1** [comment]
I am adding an option to HPCloud-deploy which will allow a variable DEMO to be provided, so if one does
```
DEMO=1 vagrant up
```

It will provision the VM as a demo cluster as well and add a demo cluster ( which will appear in the UI ). The idea is to be able get a demo up and running in one command.

This would be a good starting point for  user documentation as we could then walk them through create a project, simulation and running the simulation on the demo cluster.

**Comment by cjh1** [comment]
We should have this doc in place for our release.

**Comment by TristanWright** [comment]
cool!

On Fri, May 20, 2016 at 3:11 PM, Chris Harris <notifications@github.com>
wrote:

> I am adding an option to HPCloud-deploy which will allow a variable DEMO
> to be provided, so if one does
>
> DEMO=1 vagrant up
>
> It will provision the VM as a demo cluster as well and add a demo cluster
> ( which will appear in the UI ). The idea is to be able get a demo up and
> running in one command.
>
> This would be a good starting point for user documentation as we could
> then walk them through create a project, simulation and running the
> simulation on the demo cluster.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/issues/406#issuecomment-220719486>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
Should make local dev easier as well.

**Comment by cjh1** [comment]
We should like the user part of this work for release

**Comment by TristanWright** [comment]
closed with #496
