### ISSUE TITLE
In simulation start dialog cap the number instance in the cluster

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#42]
We have the following two endpoints:

```
GET /user/{id}/aws/profiles/{profileId}/maxinstances
GET /user/{id}/aws/profiles/{profileId}/runninginstances
```

The max number instances that a user can create in a cluster should be the result of the first request minus the second.

**Comment by TristanWright** [comment]
So should there then be a dropdown for which AWS profile to use, or are we limiting that to one?

**Comment by cjh1** [comment]
Yes, we need a drop down to select the profile.

**Comment by TristanWright** [comment]
This is in place, not sure where to send the profile that's selected though. Right now the profile._id is being returned with [the other aws parameters](https://github.com/Kitware/HPCCloud/blob/master/src/modules/cmb/core/cmb-simulation-launcher.js#L91).

**Comment by cjh1** [comment]
This will need to be sent when running a task that uses an ec2 cluster.
