### ISSUE TITLE
PyFR workflow visualization logs are not shown

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#423]
When in the visualization step of the PyFR workflow. The output files should be the files for the paraview job rather than the simulation.

**Comment by cjh1** [comment]
The screenshot attached illustrates what is currently shown.

![output](https://cloud.githubusercontent.com/assets/1031053/16269314/c5a6965a-385f-11e6-96a7-9ff35641aae5.png)

**Comment by TristanWright** [comment]
I've been checking all the parameters we're using. Based on [this line](https://github.com/Kitware/HPCCloud/blob/4954dab4a236fc6589355a7f51da689268fcac7c/src/workflows/pyfr/common/steps/Visualization/Start/index.js#L54) we have the output path (as opposed to the output girder id). SSH'ing into Ulmus that folder path has the same contents as what's showing in the output.

What do we expect in the output? We're saving `simulation.steps.Visualization.folderId` but it never has contents, is that what we should be showing?

**Comment by cjh1** [comment]
@TristanWright So it looks like there are two problems here.

- [ ] When on the Visualization step we should display the content of ```simulation.steps.Visualization.folderId```
- [ ] For some reason the outputs are not being upload. This should be happening [here](https://github.com/Kitware/HPCCloud/blob/master/server/taskflows/hpccloud/taskflow/paraview.py#L315)

**Comment by TristanWright** [comment]
Fixed with #497
