### ISSUE TITLE
The state of a simulation is not updated after it has been terminate

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#43]
Still see the green rocket, even after termination.

**Comment by TristanWright** [comment]
I think this line snuck in there: https://github.com/Kitware/HPCCloud/blob/master/src/modules/girder/kw.girder.js#L790
We're not really doing anything with meta.task anywhere else, I think it should be meta.status. It would clear up #39 too.

**Comment by cjh1** [comment]
Not sure if this is related but I'm also not seeing the state of a simulation change when it completes

**Comment by TristanWright** [comment]
Is the new status "completed" or "complete"?

**Comment by cjh1** [comment]
complete

**Comment by TristanWright** [comment]
related to #39, this might be fixed.
