### ISSUE TITLE
Allow SimPut to ingest a configuration file

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#436]
The use case here is the user has a base configuration file and they want to be able to make changes to it. So we would need to get the configuration file into the SimPut model. This would allow us to combine our "runtime" workflows with the regular SimPut workflows.

**Comment by TristanWright** [comment]
This could be done very simply if the base file was configured with Simput because ypu can export the data-model with the compiled input file.

**Comment by cjh1** [comment]
The file may not ( probably not ) be generated with Simput, so I am guessing parsing logic would have to be added to convert to the simput data-model.

**Comment by TristanWright** [comment]
So we have this in Simput. Now we need to figure out how to work it in with the project scheme we have. Should we simply unify the two pyfr project types?

**Comment by cjh1** [comment]
Yes I think that would be a good approach

**Comment by TristanWright** [comment]
So do we allow the mesh file upload on the project, and then an optional ini file for each simulation? Otherwise all the simulations will share the same ini file

**Comment by cjh1** [comment]
I think there are couple modes that would be useful here. 

- When the user creates a project they can provide a mesh and an ini file. Any simulation will use that mesh and the input would populated with the ini file model, however, they could modify the input, the changes would local to the simulation. So the project ini is like a template. Would also be nice to be able edit the project level input as well ( that could come in the future ).
- The user provide just a mesh when creating a project. They can then either upload an ini file ( then make any changes they like ) or build the input by hand.

**Comment by TristanWright** [comment]
closed with #542 🎉
