### ISSUE TITLE
Write release blog

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#440]

**Comment by TristanWright** [comment]
- [ ] simput steps
- [ ] screenshot

**Comment by TristanWright** [comment]
@cjh1 @chetnieter 

I've uploaded new screenshots for the steps. Looks pretty complete overall. Wordpress' spell checker is pretty good too, ran that on it and caught a few things. Let's look it over tomorrow again on a hangout or something.

**Comment by TristanWright** [comment]
Preview link if one of us is editing: https://blog.kitware.com/?p=15620&preview=true

**Comment by cjh1** [comment]
@TristanWright Thanks for the updates, a few things:

- The third screenshot doesn't seem to be clickable?
- I wonder if we can increase the displayed size of the images.
- The DEMO=1 looks strange the way its on separate line, can we get it to be formated inline.
- What did you do to produce the final image in ParaView, the dataset seem split?

@chetnieter Can you take a look? Particular making sure the steps make sense. You should have permission to edit it.

**Comment by chetnieter** [comment]
I just read it over and made a few minor grammar edits. I found that both the AWS profile screenshot and the 'Running the Simulation' screenshot are not clickable. I agree that the screenshot should probably be bigger. I will spend some time this morning testing the process described in the blog to see if we missed anything.

**Comment by TristanWright** [comment]
@cjh1 those are easy changes, except the DEMO=1 thing, I had the same thought yesterday.

- [x] The third screenshot doesn't seem to be clickable?

> I wonder if we can increase the displayed size of the images.

Click on an image and click the pen icon. In the window that opens afterwards there's a sidebar with "Display options" and you can set either a custom size or a predefined one.

> The DEMO=1 looks strange the way its on separate line, can we get it to be formated inline.

I agree, I was looking at it yesterday a bit. I think because it's in monospace it changes it. Alternatively we could italicize it.

> What did you do to produce the final image in ParaView, the dataset seem split? 

It's the second frame of the output with a scaler filter on it and display in wireframe. It's just a little more interesting that a dot on a plane, can easily change though.

**Comment by chetnieter** [comment]
@cjh1 Issues with blog instructions:

- There is no v0.90 tag or branch for HPCCloud-deploy
- In the status/tool bar on first screenshot "simputttt / pyfr with simput".
- It is not clear what the "Preferences page" is. I assume this is accessed by clicking on the user name at the top.
- Blog says click on "AWS" but the toolbar has EC2. Once you click on it says AWS EC2.
- Failure on saving a AWS profile gives a clear error message but having the save button remaining after success is a little confusing. Maybe give a success message or switch save to modify which returns to the original page to edit.
- Do we need to provide a link/access to a sample mesh in the blog for pyfr?
- Constants is misspelled on pyfr simulation input list (as Contstants).
- Can't edit "LDG Tau".
- After starting simulation I had to refresh the page to see the taskflow update.
- Several minutes after pressing Visualize I still don't get the ParaviewWeb tool. Just the spinner the Loading message. I have had this issue before so it may be something with my system.

**Comment by TristanWright** [comment]
> In the status/tool bar on first screenshot "simputttt / pyfr with simput".

I'll update that

**Comment by TristanWright** [comment]
> The third screenshot doesn't seem to be clickable?
@TristanWright In case you missed it in my comment above the fourth screenshot is also not clickable.

Resolved too, you can change the clickability by editing the image and changing the "Link to" option in the Display Options

**Comment by cjh1** [comment]
@chetnieter Thanks for the QA, I am going to edit your comment to convert the issue into check boxes we can check off if that is OK?

**Comment by TristanWright** [comment]
> Constants is misspelled on pyfr simulation input list (as Contstants).

@chetnieter This is fixed, you need to `npm install`

**Comment by chetnieter** [comment]
> Thanks for the QA, I am going to edit your comment to convert the issue into check boxes we can check off if that is OK?

@cjh1 Yes

**Comment by TristanWright** [comment]
@chetnieter can you move the remaining to separate issues?

**Comment by cjh1** [comment]
The tagging I can take care of. When creating them label them as "release"

**Comment by chetnieter** [comment]
> can you move the remaining to separate issues?

Yes - should I label them all release?

**Comment by cjh1** [comment]
@chetnieter Yes :smile:

**Comment by chetnieter** [comment]
Jinx

**Comment by chetnieter** [comment]
> Constants is misspelled on pyfr simulation input list (as Contstants).
> @chetnieter This is fixed, you need to npm install

@TristanWright I am running in DEMO mode so I am guessing that npm install should be run and then the new files in dist should be commited to the repo to fix it for DEMO mode?

**Comment by TristanWright** [comment]
I always feel uneasy about how we commit `dist/` files from other repositories, running `npm install` will add the new pyfr with the spelling error. We can commit it.

**Comment by chetnieter** [comment]
@TristanWright I went to re-size the screenshots in the blog and it looks like they are pretty low rez images because the look fuzzy when blown up.

**Comment by TristanWright** [comment]
@chetnieter  @cjh1 screenshots have been updated

**Comment by patrickoleary** [comment]
How do I pull the blog?

**Comment by cjh1** [comment]
@patrickoleary Was just about to send you the link and ask for your feedback, I will send you the link.

**Comment by chetnieter** [comment]
@patrickoleary @cjh1 I added Patrick as an author in case he needs that to access the blog post.

**Comment by cjh1** [comment]
Thanks @chetnieter You bet me to it!

**Comment by TristanWright** [comment]
Closed with https://blog.kitware.com/hpccloud-hpc-simulation-workflow-in-the-cloud/ 
🎉
