### ISSUE TITLE
Report HTTP errors from girder to client UI

### ISSUE THREAD

**Issue by chetnieter** [Kitware/HPCCloud#443]
An issue was discovered when working with the vagrant VM when it was stood up with the DEVELOPMENT flag. Girder failed to load the required plugins due to an old symbolic link that was pointing a non-existent directory. The client was unable to access girder so it did not display previous projects or clusters but did not make the user aware of any obvious errors. When the developer tools was open the HTTP errors showed up in the console. This HTTP errors should be handled and reported by client without having to open the developer tools.

**Comment by TristanWright** [comment]
closed with #480
