### ISSUE TITLE
Progress indicator needed while waiting for ParaViewWeb connection

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#448]
It can take several seconds for the pvpython process to start listening ( loading all the ParaView libraries take a while from an EBS volume ). The user currently sees:

![screen](https://cloud.githubusercontent.com/assets/1031053/17037264/04b3ca92-4f5e-11e6-91e4-e1acaba973b5.png)

We  should have some sort of spinner ...

**Comment by TristanWright** [comment]
Progress indicator, or loading indicator? Are there progress events for the connection we can listen to?

**Comment by cjh1** [comment]
Nope, it should just appear until the websocket connection is successful or timeout I think.

**Comment by TristanWright** [comment]
closed with #461
