### ISSUE TITLE
When in a simulation there is no indication of the current simulation workflow

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#465]
May be have a little icon near the open folder in the bread crumb bar at the top?

**Comment by TristanWright** [comment]
The active workflow/step could have some icon next to it, the rocket running icon perhaps.

**Comment by cjh1** [comment]
@TristanWright Sorry I think my description was a little misleading, I was referring the type of the workflow, i.e. PyFR, NWChem ...

**Comment by TristanWright** [comment]
How about as a title prefix?

![screen shot 2016-07-29 at 11 35 12](https://cloud.githubusercontent.com/assets/13318121/17257615/29a8dc34-5580-11e6-968c-6c30dd94aca5.png)

it looks a bit odd in the breadcrumbs 

![screen shot 2016-07-29 at 11 35 49](https://cloud.githubusercontent.com/assets/13318121/17257632/39cff55c-5580-11e6-9d65-e05cf2cd16b2.png)

**Comment by TristanWright** [comment]
(or did you mean the wf-icon in place of the folder icon?)

**Comment by cjh1** [comment]
I meant on the folder, but looking at it now, not sure that will work unless its very small. I think the prefix is   good, if we can get icon without the white backgrounds.

**Comment by TristanWright** [comment]
related to #352

**Comment by TristanWright** [comment]
fixed with #470
