### ISSUE TITLE
Clone and delete of simulation needs some progress indicator

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#47]
These operations can take several seconds. We need some sort of progress indicator otherwise I will keep clicking buttons!

**Comment by TristanWright** [comment]
disable 'clone' button until clone callback complete

**Comment by TristanWright** [comment]
Using a reduced version of this [directive](http://codepen.io/tristaaan/pen/BopLxe) I wrote.

**Comment by TristanWright** [comment]
Too simple/naive a fix, if there's one being cloned all the clone buttons are disabled, should only be disabled for that single item. reopening.
