### ISSUE TITLE
Misspelling of Volume?

### ISSUE THREAD

**Issue by chetnieter** [Kitware/HPCCloud#481]
Should Volumne [here](https://github.com/Kitware/HPCCloud/blob/master/src/panels/run/RunEC2.js#L197-L199) be Volume?

**Comment by cjh1** [comment]
Yes, feel free to push a PR with a fix.

**Comment by chetnieter** [comment]
Assuming tests pass should I go ahead merge the PR.

**Comment by cjh1** [comment]
Let @TristanWright take a look first.

**Comment by chetnieter** [comment]
Fixed by #482
