### ISSUE TITLE
File viewing 

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#499]
Should the eye icon on the file listing open the raw file in a new tab, should open in tab be an option on the modal that pops up when you click it now?

**Comment by TristanWright** [comment]
Github does some wrapping around plaintext files, for example if you try to save the [raw .ini](https://raw.githubusercontent.com/vincentlab/PyFR/develop/examples/euler_vortex_2d/euler_vortex_2d.ini) the file save dialog will end with .ini.txt.  PDF's in repos [just have a download button](https://github.com/euske/pdfminer/blob/master/samples/jo.pdf).

The two alternatives is that we have a new endpoint along the lines of `item/raw` which serves the file contents wrapped in the `pre` tag like Github. Or we add a full screen button to the FilePreview modal.

**Comment by cjh1** [comment]
@TristanWright Girder recently added this functionality, might be worth looking at what they are doing.

**Comment by TristanWright** [comment]
#505 addresses this

**Comment by TristanWright** [comment]
closed with #505
