### ISSUE TITLE
Create NWChem taskflow

### ISSUE THREAD

**Issue by chetnieter** [Kitware/HPCCloud#504]
Moving kitware/cumulus#258 to correct repo.
- [x] Install nwchem on a trad dev cluster. ( I have installed on ulmus for testing )
- [x] Develop taskflow to perform the following steps ( we can use the [PyFR taskflow](https://github.com/Kitware/HPCCloud/blob/master/server/taskflows/hpccloud/taskflow/pyfr.py) as a template
  1. Download geometry file from Girder to the cluster ( the client should pass the file id and file type )
  2. Download the ini file from Girder to the cluster ( this will be generated SimPut or uploaded by the user ) ( the client should pass the file id to the flow )
  3. Generate/template an appropriate submission script for NWChem using this input files. 
  4. Create and submit job to cluster
  5. Monitor and wait for completion
  6. Upload output to Girder ( assuming output is small )
- [ ] Update taskflow to work on EC2 by create an AMI with NWchem install on it. We should be able to use the nwchem from apt-get.

[NWChem Documentation](http://www.nwchem-sw.org/index.php/Release66:NWChem_Documentation)

The visualization step will be client based, we can look at that once the simulation steps are in place.

**Comment by cjh1** [comment]
@cryos Pointed out that we might want to provide an option to perform force field optimization using openbabel before running NWchem. NWChem many not converge if the intial geometry is to "course" ( we can do this when we have the end to end workflow working ).

**Comment by TristanWright** [comment]
Should we move the final item on this issue to a new one?

**Comment by cjh1** [comment]
Yes, lets go ahead and do this, link to this in the new issue.

**Comment by TristanWright** [comment]
moved to #582
