### ISSUE TITLE
Running EC2 outside of US-West-2 errors

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#509]
As discussed in #497

https://github.com/Kitware/HPCCloud/pull/497#issuecomment-242533697

**Comment by cjh1** [comment]
@TristanWright Try now I have copied the required AMI's to all the US regions. We should add a note to the docs that the PyFR and ParaView workflow are currently only supported in US regions and that they can contact us if they want to run in another regions and we can copy the AMIs over.

**Comment by cjh1** [comment]
Note you will need an updated cumulus.

**Comment by TristanWright** [comment]
Cool, this looks all cleared up.
