### ISSUE TITLE
Can't edit "LDG Tau" for pyfr in DEMO mode

### ISSUE THREAD

**Issue by chetnieter** [Kitware/HPCCloud#516]
When I click on the input box for LDG Tau for the pyfr simulation input it does let me enter a new value. Digging down into the elements there is an <input> tag there. I see when running with the vagrant VM in DEMO mode.

**Comment by TristanWright** [comment]
What is the tag and what new value are you trying to enter?

**Comment by TristanWright** [comment]
or you just meant there's an html tag there, scrap that question. What's the new value you're entering?

**Comment by chetnieter** [comment]
Yes - just an <input> html tag. I was trying to delete the value and leave it empty but it doesn't even appear as 'clickable' or give me a cursor when I click on it.

**Comment by TristanWright** [comment]
Oh I think I know what it is, when was the last time you pulled. 

https://github.com/Kitware/HPCCloud/issues/510

**Comment by chetnieter** [comment]
All the issues I am reporting on today come from the DEMO mode so I am:

1. Getting HPCCloud-deploy from github (did that this morning)
2. Running DEMO=1 vagrant up which I assume gets cumulus, girder and hpccloud from github during provisioning
3. Going to localhost:8080 in chrome.

Is this another case where the files in dist need to be rebuild via npm and committed? Does the vagrant/ansible provisioning run npm install or build?

**Comment by TristanWright** [comment]
it looks like it builds, 

https://github.com/Kitware/HPCCloud-deploy/blob/1cc6407d88443f7589bd95ac0ba738b1845e3652/ansible/roles/hpccloud/tasks/main.yml#L49-L55 

do you `vagrant provision` or just `up`?

**Comment by chetnieter** [comment]
`vagrant up` but doesn't that run the provisioning if it hasn't been done?

**Comment by chetnieter** [comment]
So the vagrant VM is using the master branch not the release branch of hpccloud. Is that the issue?  #510 was merged into release.

**Comment by TristanWright** [comment]
from the [graph](https://github.com/Kitware/HPCCloud/network) master should have the important part of release in it. My understanding is `up` doesn't always provision, it just starts up the vm?

**Comment by chetnieter** [comment]
I will try to run 'vagrant provision' to see if that fixes it.

**Comment by chetnieter** [comment]
So running `vagrant provision` didn't fix it and I am pretty sure that provisioning is run the first time you run `vagrant up`. I was able to enter/delete values in the input box if I clicked on the question mark to open the help text so I bet it is related to #510.

**Comment by TristanWright** [comment]
There's just an absolute positioned element over the box. Merge into master will fix.

**Comment by chetnieter** [comment]
Checked and confirmed this was fixed by #517.
