### ISSUE TITLE
Switching from PyFR to PyFR(runtime) project doesn't hide mesh upload option

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#522]
PyFR

![one](https://cloud.githubusercontent.com/assets/1031053/18635602/99673718-7e53-11e6-8597-c1b12027e8aa.png)

switch to PyFR(runtime)

![two](https://cloud.githubusercontent.com/assets/1031053/18635611/9f50b672-7e53-11e6-996f-ce60558e3848.png)

**Comment by TristanWright** [comment]
closed with #523
