### ISSUE TITLE
Unable to rerun viz with demo vm

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#526]
So I was able run the pyfr workflow including the viz with the latest RC, however, if I terminate the paraview job and then rerun I am unable to connect the the paraviewweb session.

**Comment by cjh1** [comment]
@TristanWright Could take a look?

**Comment by TristanWright** [comment]
fixed in #529 
When we click rerun we were deleting the taskflow, but on the visualization page we [weren't updating the metadata object](https://github.com/Kitware/HPCCloud/pull/529/files#diff-c7de245208dadcdd0d6f4902dad5a824R67).
