### ISSUE TITLE
Problems running visualization of pyfr on DEMO cluster

### ISSUE THREAD

**Issue by chetnieter** [Kitware/HPCCloud#530]
After running the pyfr simulation I never see (> 10 min waiting) the paraview viz tool load. It is just stuck on the loading screen. I see the following in the console.

```
WebSocket connection to 'ws://localhost:8888/proxy?sessionId=MC42MDI1MDM2NzQzMzU0Nzk5LDAuNzQ5ODAxNDA1MTY5MDQ3NiwwLjc2NzE2NzM3MjEyODU1Nw==&path=ws' failed: Error during WebSocket handshake: Unexpected response code: 400
```

After returning to the simulation page it gives me the option to re-run the visualization. It now freezes up before finishing the start up of the paraview taskflow and I see this in the console.

```
HPCCloud.js:5 Uncaught (in promise) TypeError: Cannot read property 'taskflowId' of undefined
```

**Comment by TristanWright** [comment]
#529 fixes the latter error.

**Comment by chetnieter** [comment]
I was unable to reproduce this issue with the `v09-rc2` tag after three attempts so I am going to close the issue.
