### ISSUE TITLE
Better component composability to reduce duplication across workflows.

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#544]
https://facebook.github.io/react/docs/component-specs.html#mixins
https://facebook.github.io/react/docs/pure-render-mixin.html

**Comment by cjh1** [comment]
@TristanWright Here we go

**Comment by cjh1** [comment]
I am going to start using this issue to keep track of code that I think we can refactor for reuse.

**Comment by cjh1** [comment]
[This function](https://github.com/Kitware/HPCCloud/blob/master/src/workflows/pyfr/pyfr-simput/components/steps/Input/index.js#L58-L110) is duplicated between the PyFR and NWChem workflows.

**Comment by sbhtw** [comment]
Just a short note, Facebook doesn't recommand using mixins anymore, see

* <https://facebook.github.io/react/docs/reusable-components.html#mixins> and
* <https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html>

**Comment by cjh1** [comment]
@sbhtw Thanks for the note and links, I will let @TristanWright take a look at them as he had initial mention mixins.

**Comment by TristanWright** [comment]
Thanks for forwarding that @sbhtw 👍

**Comment by TristanWright** [comment]
RunSimulation panels always build the taskflow start packets in them, we can move these into helper functions to pass to a generic panel

https://github.com/Kitware/HPCCloud/blob/master/src/workflows/pyfr/common/steps/Simulation/Start/index.js#L51

**Comment by TristanWright** [comment]
closed with #579 ⭐️⭐️⭐️⭐️⭐️
