### ISSUE TITLE
Add support for canceling network requests

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#545]
[axios](https://github.com/mzabriskie/axios) supports canceling, we should expose this in our client.

**Comment by TristanWright** [comment]
ooo cool! Looks like they've [added a lot](https://github.com/mzabriskie/axios/blob/master/CHANGELOG.md) since the version we're currently using (0.9), where would it be appropriate to use cancels right now?

**Comment by cjh1** [comment]
I was loading some data from the server in a ```componentDidMount``` function and the request should be aborted in the ```componentWillUnmount``` ( if its not completed ), there are probably many place we could make use of it as well.

**Comment by TristanWright** [comment]
closed with #561
