### ISSUE TITLE
Status event broadcast seems to fail sometimes

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#55]
I see the following in the console:
```
broadcasting SSE: task.status running
```
However, the simulation status is not updated

**Comment by TristanWright** [comment]
I haven't seen this reproduced in a while have you?

**Comment by cjh1** [comment]
no, not recently

**Comment by TristanWright** [comment]
Closing...

**Comment by cjh1** [comment]
So I have been looking at this. It looks to me like the browser in certain situations is not reconnecting to the event stream after it times out. I am currently not sure why.

**Comment by cjh1** [comment]
Ok, so I have steps to recreate this. Load HPC Clound app in a tab and then switch to another tab. For what ever reason chrome fails to reconnect after the 5 minute timeout. Looks like other people have had similar issues. I will look at using [this] (https://github.com/Yaffle/EventSource)

**Comment by TristanWright** [comment]
odd, does ff do the same thing? yay polyfills

**Comment by cjh1** [comment]
yes, it looks like it has similar problems as well. The problem with the polyfill is you have to send status message from the server every 30 seconds. Would like to avoid this traffic.

**Comment by TristanWright** [comment]
I've seen 10 minute jobs get the 'complete' SSE. Closing...
