### ISSUE TITLE
PyFr/components/steps/Input

### ISSUE THREAD

**Issue by jourdain** [Kitware/HPCCloud#573]
That React component expect always to have an ini file within girder to replace its content.
So when no ini file is provided, that page will fail uploading the content.

Moreover, it could be good to rework the code logic as some stuff does not seems to make sense.

**Comment by jourdain** [comment]
For instance that was the part of code that was used to hide the backend section.

```
jsonData = jsonData = {
              data: parsedIni,
              type: 'pyfr',
              external: { 'boundary-names': boundaryNames },
              hideViews: ['backend'],
            };
```

But we can see that first line is invalid...

**Comment by TristanWright** [comment]
surprised eslint's [no-self-assign](http://eslint.org/docs/rules/no-self-assign) doesn't catch that or have something to catch that.
