### ISSUE TITLE
Cluster terminate messages are not displayed in cluster log

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#597]

**Comment by TristanWright** [comment]
Seems we're not getting the `terminating` message either?

![screen shot 2017-06-07 at 17 04 07](https://user-images.githubusercontent.com/13318121/26905247-8a042844-4ba3-11e7-88cf-899215d54d9d.png)

**Comment by TristanWright** [comment]
I'm seeing this more as a cumulus issue now. I'm not seeing the termination messages when both branches are on master either.

**Comment by TristanWright** [comment]
Moved to [cumulus #317](https://github.com/Kitware/cumulus/issues/317)
