### ISSUE TITLE
Error 500 when creating a new project

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/HPCCloud#618]
Hi,

I am running _HPCCloud_ using _HPCCloud-deploy_ VM and the associated `ComputeNode` VM.
The build of these two VMs ran smoothly however I am not able to create a new project.

Being on the Project page,  I select a project type and enter all the required information.
When I click _create project_, nothing happen and I got the following message in the console:
```
{  
   "message":"TypeError: TypeError('update() takes exactly 4 arguments (3 given)',)",
   "trace":[  
      [  
         "/opt/hpccloud/girder/girder/api/rest.py",
         619,
         "endpointDecorator",
         "val = fun(self, args, kwargs)"
      ],
      [  
         "/opt/hpccloud/girder/girder/api/rest.py",
         1220,
         "PATCH",
         "return self.handleRoute('PATCH', path, params)"
      ],
      [  
         "/opt/hpccloud/girder/girder/api/rest.py",
         960,
         "handleRoute",
         "val = handler(**kwargs)"
      ],
      [  
         "/opt/hpccloud/girder/girder/api/describe.py",
         689,
         "wrapped",
         "return fun(*args, **kwargs)"
      ],
      [  
         "/opt/hpccloud/girder/girder/api/access.py",
         63,
         "wrapped",
         "return fun(*args, **kwargs)"
      ]
   ],
   "type":"internal"
}
```

Thanks for your help

**Comment by cjh1** [comment]
@felixveysseyre I am pretty sure this is an upstream regression in Girder, I have pushed a PR that should fix it girder/girder#2464, this should be merged soon. Then you should recreate your VM, so you get the new version of Girder or I can give you instruction to pull just the latest master.

**Comment by felixveysseyre** [comment]
Thanks @cjh1 !

Your PR having been merged, should I do something else than just rebuild the main VM of HPCCloud-deploy ?

**Comment by cjh1** [comment]
@felixveysseyre Rebuild the main VM.
