### ISSUE TITLE
Modify simulation files for OpenFoam

### ISSUE THREAD

**Issue by dealenx** [Kitware/HPCCloud#632]
Hello, how can I modify files run.sh and openfoam_run , which preparing for OpenFoam simulation?

**Comment by jourdain** [comment]
I'm guessing that you are talking about that [file](https://github.com/Kitware/simput/blob/227a67d6bd744a486a4ffb896ebb7b728a245785/src/templates/run.hbs)?

**Comment by dealenx** [comment]
Yes, that's it, thanks!

And one more question. 

I changed [comands](https://github.com/dealenx/HPCCloud/blob/b448893442adf2a01e9211b24300397abdbcc2f7/server/taskflows/hpccloud/taskflow/openfoam/tutorial.py#L86) in `@cumulus.taskflow.task` for openfoam_run, for example,  just i had added a line for creating a .txt file. 

But after starting a simulation, I expected to see:
```
chmod +x $PWD/run.sh
touch test.txt
xhost +local:of_v1612_plus
docker start of_v1612_plus
docker exec -t of_v1612_plus $PWD/run.sh $PWD
```

but i had seen output of openfoam_run:
```
chmod +x $PWD/run.sh
xhost +local:of_v1612_plus
docker start of_v1612_plus
docker exec -t of_v1612_plus $PWD/run.sh $PWD
```

I don't know, the commands for the file openfoam_run are in another place or I did't build the server correctly?

**Comment by jourdain** [comment]
I'm guessing the issue might be in the build process especially since we are missing documentation and it is not as trivial as we hope it to be. (But we are working on improving it. ;-)

Can you provide some background on what you do build/deploy your code base?

**Comment by dealenx** [comment]
I build hpccloud with modified files  for running OpenFoam simulations on university computing cluster.

**Comment by jourdain** [comment]
Are you using the docker infrastructure? Or do you build and deploy each piece yourself?

**Comment by dealenx** [comment]
I am using docker infrastructure from a rep [hpccloud-services](https://github.com/Kitware/hpccloud-services).

I changed lines: [/docker/girder/Dockerfile](https://github.com/Kitware/hpccloud-services/blob/71fbddff7fd8bd758e08ca5ee1ef2f1573d01474/docker/girder/Dockerfile#L26) and [/docker/girder/Dockerfile](https://github.com/Kitware/hpccloud-services/blob/3f571449e73e27b52f6f68437fae0664c00c5622/docker/celery/Dockerfile#L35)

Changes from `https://github.com/Kitware/HPCCloud.git` to `https://github.com/dealenx/HPCCloud.git`

**Comment by jourdain** [comment]
Did you clear your docker cache when you rebuilt the images? @patrickoleary should know better.

**Comment by dealenx** [comment]
I did run command `sudo docker-compose build --no-cache` and i had watching for logs, i had seen that cloning comes from https://github.com/dealenx/HPCCloud.git , but after the openfoam simulation output of `openfoam_run` was not changed.

I did build yesterday, but I need to double-check today, there is a possibility that I can make a mistake when i using docker-compose.

**Comment by dealenx** [comment]
I learned more about Docker, i compiled and restarted using command:
```
docker-compose up -d --build girder
```
