### ISSUE TITLE
Change spinning gear to something meaningful and informative.

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#68]

**Comment by TristanWright** [comment]
Monitor job status somehow.

**Comment by TristanWright** [comment]
Can you determine progress from the `job.status` event sequence?

- downloading - 20%
- queued - 40%
- running - 60%
- queued - 80%
- running - 100%

**Comment by cjh1** [comment]
Sadly no, its not possible to know the progress in terms of a percentage

**Comment by TristanWright** [comment]
Be sure it's consistent between tagger and vizer

**Comment by TristanWright** [comment]
The above sequence is for the visualize task (ends on `running`). The tagger task is a different sequence and ends on `complete`. So for the viz task what's the flag that signifies it's ready?

**Comment by cjh1** [comment]
I made that change to the viz task as I thought is made more sense that the task stayed in the running state, as its not really complete unless someone terminates it. I guess I didn't make the same change for the tagger. Lets discuss what would be the best approach for the UI.

**Comment by TristanWright** [comment]
In the VM is there an elegant way to update cumulus and girder?

On Tue, Oct 20, 2015 at 7:23 AM, Chris Harris <notifications@github.com>
wrote:

> I made that change to the viz task as I thought is made more sense that
> the task stayed in the running state, as its not really complete unless
> someone terminates it. I guess I didn't make the same change for the
> tagger. Lets discuss what would be the best approach for the UI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/issues/68#issuecomment-149567139>.
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
You can add the following to your Vagrantfile in the  config.vm.provision "ansible" do |ansible| block, after line 73:

```
ansible.tags = ["cumulus", "girder"]
```

Then run:

```
vagrant provision
```

**Comment by cjh1** [comment]
We still need some sort of progress indicator in the mesh tagger its several seconds after we switch to the mesh tagger before we see the mesh ...
