### ISSUE TITLE
Use SSE event for status updates

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#7]
So once Kitware/cumulus#35 is merged the backend will produce server side events for status update, this should reduce the amount of polling that we will need to do in the UI. There might be some nice angular way of access these events, but here is some sample code in raw javascript.

```javascript
        if (window.EventSource) {
            // The timeout is the number of second we should wait without an event before closing the connection ...
            url = girder.apiRoot + '/notification/stream?timeout=300';

            var eventSource = new window.EventSource(url);

            eventSource.onmessage = function (e) {
                var obj;
                try {
                    obj = window.JSON.parse(e.data);
                } catch (err) {
                    console.error('Invalid JSON from SSE stream: ' + e.data + ',' + err);
                    return;
                }
                /* Do something useful with the event. See description of event object below */
            };
        } else {
            console.error('EventSource is not supported on this platform.');
        }
```
The event object have the following form:

```javascript
{
  "type": "<profile.status|job.status|cluster.status|task.status>",
  "data": {
    "_id": "<the id of the resource>",
    "status": "the new status"
  }
  // There are other property but these can be ignored for our purposes
}
```

**Comment by cjh1** [comment]
It probably makes sense to add a onmessage function that then broadcast these events using the type on the rootScope, so then we can listen to the particular type we are interested in.

**Comment by TristanWright** [comment]
Added [this block](https://github.com/Kitware/HPCCloud/blob/ae0dc2b8422081852baa8b0d9fae3413c575a5e1/src/modules/girder/kw.girder.js#L41) to start. 

A `$scope.$on` will listen for these on lines like these: 

- [cmb-simulation-controller](https://github.com/Kitware/HPCCloud/blob/ae0dc2b8422081852baa8b0d9fae3413c575a5e1/src/modules/cmb/core/cmb-simulation-controller.js#L10)
-  [cmb-project-controller](https://github.com/Kitware/HPCCloud/blob/ae0dc2b8422081852baa8b0d9fae3413c575a5e1/src/modules/cmb/core/cmb-project-controller.js#L10)

**Comment by cjh1** [comment]
When create EventSource the url should be of the form:

<apiRoot>/notification/stream ( apiRoot in our case is 'api/v1' )
