### ISSUE TITLE
"Skipping tail of [file] as it currently doesn't exist" goes forever in log.

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#73]
![screen shot 2015-10-08 at 15 21 53](https://cloud.githubusercontent.com/assets/13318121/10380504/647a6a9a-6dd1-11e5-881b-27a71c453905.png)

ideas @cjh1?

**Comment by cjh1** [comment]
When you say forever do you mean the life time of the task? If so this is correct behavior. In a task you can define output files that you want to tail in this case stat.txt. As we are using a dummy script this file is not produced, so we get these messages. We will however have to add back the functionality that displays these tailed files as some point in the future.

**Comment by TristanWright** [comment]
I haven't seen a task complete with this message going on. Or maybe I should wait more than 10 mins.
