### ISSUE TITLE
ulex is hardcoded as websock hostPort!

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#82]
We need to use window.location.host

**Comment by TristanWright** [comment]
Right, I believe it was changed because of some forwarding issues. Will the forwarding be ok if this is changed back?

**Comment by cjh1** [comment]
Yes, that should now work.

**Comment by TristanWright** [comment]
localhost:8888 doesn't work for me so I'll still be hardcoding `ulex` on my copy.

**Comment by cjh1** [comment]
You would need to add a proxy rule to route it through the ulex. Normally you would be pointing your browser at ulex ...
