### ISSUE TITLE
Register button doesn't work

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#87]
When you click on register nothing seems to happen, we stay on the same page, see attached image.
![screen](https://cloud.githubusercontent.com/assets/1031053/10527831/a6e54fc8-7360-11e5-9d1c-b541c30540ca.png)

**Comment by cjh1** [comment]
it looks like an account if created, maybe we are just missing a redirect?

**Comment by TristanWright** [comment]
This might have been broken with fixing #1, I believe it was the only route I didn't test.
