### ISSUE TITLE
If the mesh tagger fails we need to report this to the user

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#89]
Currently we just site trying to connect to the PVW session.

**Comment by cjh1** [comment]
We should probably create and item each time we run the mesh tagger and pass this to the task. In the event of a failure the files uploaded to this item should be accessible to the user. Like the output section when a simulation is run.

**Comment by cjh1** [comment]
OK, so this goes for the visualizer task as well. We need to provide a mechanism to report errors during the viz or mesh tagger task. Currently we see the status updates, however, if the task ends up in an error state the user needs to be able view the output. The output is uploaded to an item, who's id is passed into output.item.id when that task is run. I suggest that as part of running a task we create a new item and pass this as the item id. Here is how a [item can be created](https://github.com/Kitware/HPCCloud/blob/master/src/modules/girder/kw.girder.js#L365-L380), we can pass in the project folder id as the parent. Then is an error occurs the output upload should be displayed on the status view ( like it is for a simulation ) [here is where we do that for a simulation](https://github.com/Kitware/HPCCloud/blob/master/src/modules/cmb/core/cmb-project-controller.js#L324).

**Comment by TristanWright** [comment]
Initial work in a3a5100, `log.$ref` shows for task. Does not show output files yet.

**Comment by TristanWright** [comment]
Is there an elegant way to prevent the newly created item to show up with the other items on the project page?
