### ISSUE TITLE
You can delete clusters while tasks are running

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#99]
Once they are deleted you cannot modify the tasks that are bound to it.

**Comment by TristanWright** [comment]
Is there a way to get tasks on a cluster without iterating through all active tasks checking for a cluster _id?

**Comment by cjh1** [comment]
No, currently that is the only way to do it.

**Comment by TristanWright** [comment]
Related #239, #238

**Comment by TristanWright** [comment]
#323 closes
